### ISSUE TITLE
filterRelationship

### ISSUE THREAD

**Issue by sanvolter** [rxcod9/joy-voyager-datatable#21]
Hi,

It's very interesting project. Are You going to finish it ?
Without working filters the usefulness of the solution is very limited.

protected function filterRelationship(
        $query,
        $keyword,
        DataRow $row,
        DataType $dataType,
        Request $request
    ): void {
        // @TODO Not implemented yet.
    }

**Comment by rxcod9** [comment]
@sanvolter 
Meanwhile you can create an scope for the data row field and it will work as filter 

https://github.com/rxcod9/joy-voyager-datatable/blob/24971aa08280dd69595ca59fcafdd966de966b2e/src/Services/Filter.php#L37

PRs are welcome 🙏

**Comment by sanvolter** [comment]
Maybe it will be useful to someone:
  

protected function filterRelationship(
        $query,
        $keyword,
        DataRow $row,
        DataType $dataType,
        Request $request
    ): void {
        
                $search_value = '%'.$keyword.'%';
                $search_filter = 'LIKE';
                $relationshipIds = [];
                    if ($row->type == 'relationship' && isset($row->details) && $row->details->type == 'belongsTo'){
                            $relationshipIds = DB::table($row->details->table)
                                ->select($row->details->key, $row->details->label)
                                ->where($row->details->label, $search_filter, $search_value)
                                ->pluck($row->details->key)
                                ->toArray();
                    }
                    $query->whereIn($row->details->column,$relationshipIds);

    }
